import Link from "next/link";
import { redirect } from "next/navigation";
import { toggleSavedContent } from "../../community/actions";
import { createClient, getCurrentUser } from "../../../lib/supabase/server";
import { fieldNotes } from "../../../data/field-notes";
import { resolveRelatedContent } from "../../../lib/content-options";

function resolveSaved(type: string, id: string) { if (type === "field-note") { const note = fieldNotes.find((item) => item.id === id); return note ? { label: note.title, href: `/field-notes/${note.slug}` } : null; } return resolveRelatedContent(type, id); }
export default async function SavedPage() { const user = await getCurrentUser(); if (!user) redirect("/sign-in?next=/profile/saved"); const supabase = await createClient(); const { data: profileId } = supabase ? await supabase.rpc("current_profile_id") : { data: null }; const { data } = supabase && profileId ? await supabase.from("saved_content").select("content_type,content_id,created_at").eq("profile_id", profileId).order("created_at", { ascending: false }) : { data: [] }; const saved = (data || []).map((row: any) => ({ ...row, item: resolveSaved(row.content_type, row.content_id) })).filter((row: any) => row.item); return <main id="main-content" className="page-shell profile-list"><Link className="back-link" href="/profile">← Profile</Link><p className="eyebrow">Personal library</p><h1>Saved Content</h1>{saved.length ? <div className="saved-list">{saved.map((row: any) => <article key={`${row.content_type}-${row.content_id}`}><div><span>{row.content_type}</span><h2><Link href={row.item.href}>{row.item.label}</Link></h2></div><form action={toggleSavedContent.bind(null, row.content_type, row.content_id, "/profile/saved")}><input type="hidden" name="action" value="remove" /><button type="submit">Remove</button></form></article>)}</div> : <div className="community-empty"><h2>Your saved collection is empty.</h2><p>Save scriptures, practices, places, audio, or field notes as you explore.</p></div>}</main>; }
