import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AudioPlayer } from "../../../components/AudioPlayer";
import { PracticeTimer } from "../../../components/PracticeTimer";
import { CommunityDiscussionPanel } from "../../../components/CommunityDiscussionPanel";
import { SaveContentButton } from "../../../components/SaveContentButton";
import { getPractice, practices } from "../../../data/practices";
import { getRecording } from "../../../data/recordings";

export function generateStaticParams() { return practices.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const practice = getPractice((await params).slug); if (!practice) return {}; return { title: practice.title, description: practice.description, alternates: { canonical: `/practice/${practice.slug}` }, openGraph: { title: practice.title, description: practice.description, type: "article" } }; }

export default async function PracticeEntryPage({ params }: { params: Promise<{ slug: string }> }) { const practice = getPractice((await params).slug); if (!practice) notFound(); const audio = practice.audioId ? getRecording(practice.audioId) : undefined; return <main id="main-content" className="practice-entry"><header className="page-hero page-shell"><Link className="back-link" href="/practice">← All practices</Link><p className="eyebrow">{practice.category} · {practice.durationMinutes} min · {practice.provenance || practice.historicalStatus}</p><h1>{practice.title}</h1><p>{practice.description}</p>{practice.traditionContext?.length ? <div className="tag-list">{practice.traditionContext.map((tradition) => <span key={tradition}>{tradition}</span>)}</div> : null}<SaveContentButton type="practice" id={practice.id} returnPath={`/practice/${practice.slug}`} /></header><section className="practice-room page-shell"><div><h2>Instructions</h2><ol>{practice.instructions.map((instruction) => <li key={instruction}>{instruction}</li>)}</ol><p className="editorial-note">{practice.editorialNote}</p>{practice.sources?.length ? <div className="practice-sources"><h3>Sources &amp; license</h3>{practice.sources.map((source) => <div className="source-record" key={source.id}><strong>{source.title}</strong>{source.author ? <p>{source.author}</p> : null}{source.url ? <a className="text-link" href={source.url} target="_blank" rel="noreferrer">Read source ↗</a> : null}{source.rights ? <small>{source.rights}</small> : null}{source.note ? <p>{source.note}</p> : null}</div>)}</div> : null}</div><PracticeTimer practice={practice} /></section>{audio ? <section className="page-shell practice-audio"><AudioPlayer recording={audio} /></section> : <section className="page-shell practice-audio"><p className="placeholder-panel">[AUDIO OR GUIDANCE TO BE ADDED AFTER EDITORIAL AND RIGHTS REVIEW]</p></section>}<div className="page-shell"><CommunityDiscussionPanel type="practice" id={practice.id} label="this practice" /></div></main>; }
