import type { Metadata } from "next";
import Link from "next/link";
import { guideEntries, guideSections } from "../../data/guide";

export const metadata: Metadata = { title: "A Guide to Buddhism", description: "Traditions, texts, practices, and terms encountered throughout Scripture in Sound.", alternates: { canonical: "/guide" }, openGraph: { title: "A Guide to Buddhism", description: "An orientation to traditions, texts, practices, and terms used throughout Scripture in Sound.", type: "website" } };

export default function GuidePage() {
  return <main id="main-content"><header className="page-hero page-shell"><p className="eyebrow">Orientation</p><h1>A Guide to Buddhism</h1><p>Traditions, texts, practices, and terms encountered throughout Scripture in Sound. This is a concise orientation layer, not a comprehensive textbook or a substitute for tradition-specific study.</p></header><nav className="guide-index page-shell" aria-label="Guide sections">{guideSections.map((section, index) => <a href={`#${section.id}`} key={section.id}><span>{String(index + 1).padStart(2, "0")}</span>{section.title}</a>)}</nav><div className="page-shell guide-sections">{guideSections.map((section, sectionIndex) => { const entries = guideEntries.filter((entry) => entry.section === section.id); return <section className="guide-section" id={section.id} key={section.id}><header><span>{String(sectionIndex + 1).padStart(2, "0")}</span><div><h2>{section.title}</h2><p>{section.description}</p></div></header>{section.id === "traditions" ? <div className="tradition-map" aria-label="Historical relationships among selected Buddhist traditions"><div className="tradition-node tradition-node--wide">Early Buddhist histories</div><span>multiple historical developments ↓</span><div className="tradition-branches"><div>Theravāda</div><div>Mahāyāna <small>wide family of texts and traditions</small><strong>↳ Vajrayāna developed within broader Mahāyāna contexts</strong></div></div><p>Regional traditions overlap these categories rather than fitting into isolated boxes.</p></div> : null}<div className="guide-grid">{entries.map((entry) => <Link className="guide-card" href={`/guide/${entry.slug}`} key={entry.id}><div><h3>{entry.title}</h3>{entry.alternateTerm ? <p className="guide-card__alternate">{entry.alternateTerm}</p> : null}</div><p>{entry.summary}</p><span>Read context →</span></Link>)}</div></section>; })}</div><section className="guide-method"><div className="page-shell"><p className="eyebrow">How this website works</p><h2>One archive, four connected perspectives.</h2><div className="method-chain">{[{title:"Scripture",text:"the textual tradition"},{title:"Sound",text:"recitation, chanting, pronunciation, and listening"},{title:"Practice",text:"contemplative engagement"},{title:"Place",text:"Buddhism lived in communities and physical environments"}].map((item, index) => <div key={item.title}><span>{String(index + 1).padStart(2,"0")}</span><strong>{item.title}</strong><p>{item.text}</p></div>)}</div></div></section></main>;
}
